### ISSUE TITLE
Query Should Use WordPress Properties

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-micropub#52]
With properties like mf2_content, it really should fetch post content for two reasons.

1. If I change the post in the editor, it does not update this field.
2. If I try to update a post that was not originally published via Micropub, I can't.

**Comment by dshanske** [comment]
To add to this, should mf2_content be stored at all for the same reason? Where a mf2 property matches with a property in the post table specifically...should both be stored?

**Comment by snarfed** [comment]
> If I change the post in the editor, it does not update this field.
> If I try to update a post that was not originally published via Micropub, I can't.

good points! fixing these would be a substantial project. we'd need to do one of:

1. hook into every way that posts/pages are edited and update the stored mf2 properties to match
1. update stored mf2 properties lazily, on a micropub query or POST
1. stop storing mf2 properties entirely, and instead generate them programmatically from the data in the wp_posts table

i'm inclined to go with #1...but i hate duplicating data, since the copies inevitably skew, so i'm open to thoughts.

again though, this is definitely the most ambitious of all the issues you've filed recently. maybe consider starting with some of the others first!

> To add to this, should mf2_content be stored at all for the same reason? Where a mf2 property matches with a property in the post table specifically...should both be stored?

yes. it already currently works this way. docs: https://github.com/snarfed/wordpress-micropub#other

**Comment by dshanske** [comment]
Why not generate them from the post table? It seems the easiest.

**Comment by dshanske** [comment]
If we hook onto the get_post_meta filter, anyone asking for mf2_content would get post content

**Comment by snarfed** [comment]
content, maybe, sure...but there are dozen(s) of other supported mf2 properties too! not to mention that we can get properties we don't know about at all, and we might still want to store and return them. (asked @aaronpk [about this in IRC today](https://chat.indieweb.org/dev/2017-01-17/1484688325173000); we're not sure.)

the next step here is probably to catalog all the props we currently support and whether/how we'd generate and return them from wordpress's own post data.

...but again, having said that, i definitely recommend tackling some of the other smaller issues first!

**Comment by dshanske** [comment]
I agree on not tackling this now, but keeping the issue on the list.

**Comment by dshanske** [comment]
I think I may revisit this one by creating a list

**Comment by dshanske** [comment]
I'm mapping in Post Kinds/Parse This and @pfefferle is doing this in MF2-feed

**Comment by dshanske** [comment]
Revisiting this issue.

Believe the following items should not be stored in meta, but extracted from their WP_Post equivalents when queries.

WP to MP
- post_title maps to name
- post_date/post_date_gmt maps to published
- post_content maps to content
- post_excerpt maps to summary
- post_modified/post_modified_gmt maps to updated

**Comment by pfefferle** [comment]
seems to reduce complexity and duplications.

**Comment by dshanske** [comment]
@pfefferle Implemented this last night... introduced some complexity due timezone offset no having to be stored, but still...

**Comment by pfefferle** [comment]
yes, have seen your merge request.
