### ISSUE TITLE
set post author

### ISSUE THREAD

**Issue by snarfed** [indieweb/wordpress-micropub#62]
...i thought the plugin already did this, so maybe it's a bug that it doesn't? feature request from @anomalily at IWS 2017 when she saw that OwnYourSwarm checkin posts don't have an author set.

**Comment by lostfocus** [comment]
That happens when the `website` field in `/wp-admin/profile.php` isn't set.

**Comment by snarfed** [comment]
huh! interesting. thanks for finding!

any interest in tackling this, @lostfocus? relevant places to start are below. i'd be happy to cut a release and push to the wordpress.org plugin directory afterward!

https://github.com/snarfed/wordpress-micropub/blob/269c9150f5aa7c8b820fc236c9db239f91cc8cf3/micropub.php#L324

https://github.com/snarfed/wordpress-micropub/blob/269c9150f5aa7c8b820fc236c9db239f91cc8cf3/tests/test_micropub.php#L323

**Comment by lostfocus** [comment]
I'm not too sure this needs tackling - it pretty much works as intended:

https://github.com/snarfed/wordpress-micropub/blob/269c9150f5aa7c8b820fc236c9db239f91cc8cf3/micropub.php#L201

So there are basically two options: put that info into the readme or find some other way to decide which WordPress user is the right one. (Since you are planning to add a settings page in #72 - maybe it's a good idea to select a default user there?)

**Comment by dshanske** [comment]
Why not use the author url when the user URL isn't set? Which is set by default to /author/user?

**Comment by dshanske** [comment]
https://developer.wordpress.org/reference/classes/wp_rewrite/get_author_permastruct/

**Comment by dshanske** [comment]
This will be done by the IndieAuth plugin once it is deployed, by the way.

**Comment by dshanske** [comment]
This should now be addressed. Resolved in 2.0.0
